AWSTemplateFormatVersion: 2010-09-09

Description: |
  This is the web server for a decimal to roman numerial converter. 
  Creates an EC2 instance with a user data that installs flask and runs
  an application to convert decimal to roman numerials.

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the key pair you want to use for this web server.

  MySecurityGroup:
    Description: My securit group name for web server.
    Type: AWS::EC2::SecurityGroup::GroupName

Resources:
  RomanNumerialServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e731c8a588258d0d
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: decimal-roman-converter
      UserData:
        !Base64 |
          #!/bin/bash
          dnf update -y
          dnf install git python3-pip -y
          pip install Flask
          cd /home/ec2-user
          git clone https://github.com/richer-tan/Project-001-Roman-Numerals-Converter.git app
          cd app
          python3 app.py
          
Outputs:
  PublicIPAddress:
    Description: The puplic IP of my instance.
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt RomanNumerialServer.PublicIp